const TEMPLATE = {
  TITLE: 'TITLE',
  DESCRIPTION: 'DESCRIPTION',
  COMPONENT_NAME_EXAMPLE: 'COMPONENT_NAME_EXAMPLE',
  HTML_TEMPLATE_USAGE: 'HTML_TEMPLATE_USAGE',
  PROPERTIES: 'PROPERTIES',
  EVENTS: 'EVENTS',
  CSS_CUSTOM_PROPERTIES: 'CSS_CUSTOM_PROPERTIES',
};

const PROJECTS_PATH = `${__dirname}/../projects/components/src/lib`;

module.exports = {
  TEMPLATE,
  PROJECTS_PATH,
};
